### ISSUE TITLE
Interesting Stack Trace during testing

### ISSUE THREAD

**Issue by MichalKononenko** [MichalKononenko/MrFreeze#27]
This error was thrown when trying to measure from a LHe gauge that was off. Does this only happen if the meter is off?

```
Error
Traceback (most recent call last):
  File "/home/mkononen/git/MrFreeze/tests/integration/test_devices/test_cryomagnetics_lm510.py", line 81, in test_channel_to_measure
    self._test_channel_1()
  File "/home/mkononen/git/MrFreeze/tests/integration/test_devices/test_cryomagnetics_lm510.py", line 88, in _test_channel_1
    self.instrument[0].measurement
  File "/home/mkononen/git/MrFreeze/mr_freeze/devices/cryomagnetics_lm510.py", line 145, in measurement
    self._prepare_measurement()
  File "/home/mkononen/git/MrFreeze/mr_freeze/devices/cryomagnetics_lm510.py", line 202, in _prepare_measurement
    "Data not ready. Received response {0}".format(response))
mr_freeze.exceptions.DataNotReadyError: Data not ready. Received response meas: Command blocked
```

**Comment by MichalKononenko** [comment]
This is occurring because the LHe sensor is warm.
